---

  - hosts: all
    become: true
    tasks:

    - name: yum packet index'ini güncelleme
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: apache yükleme
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"


    - name: ensure httpd is running
      service:
        name: httpd 
        state: started
      when: ansible_distribution == "CentOS"


    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_distribution == "CentOS"


    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: stopped
      when: ansible_distribution == "CentOS"


    - name: php kütüphanesi yükleme
      yum:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"
   
