---

    - hosts: all
      become: true
      tasks:

      - name: yum packet index'ini güncelleme
        yum:
          update_cache: yes
      - name: vim yukleme playbook ile kurulumu
        yum:
          name: vim

          
